version: '3'

services:
  tileserver-gl:
    image: maptiler/tileserver-gl:v4.12.0
    restart: always
    networks:
      - web
    volumes:
      - ./data:/data
    command: -c /data/config.json

networks:
  web:
    external: true
