version: '3'

services:
  tileserver-gl:
    image: maptiler/tileserver-gl:v3.1.0
    restart: always
    networks:
      - web-proxy
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web-proxy"
      - "traefik.http.routers.tileserver.entryPoints=websecure"
      - "traefik.http.routers.tileserver.rule=Host(`$URL`)"
      - "traefik.http.services.tileserver.loadbalancer.server.port=8080"
    command: -c /data/config.json

networks: 
  web-proxy:
    external: 
      name: web-proxy
